import { ApiMovie, ApiName, ApiPrincipal } from "./types";

export const MOCK_MOVIES: ApiMovie[] = [
  {
    tconst: "tt0017162",
    title_type: "movie",
    title: "Moana",
    original_title: "Moana",
    is_adult: false,
    year: "1926",
    end_year: null,
    runtime: "85",
    genre: "Documentary",
  },
  {
    tconst: "tt0029583",
    title_type: "movie",
    title: "Snow White and the Seven Dwarfs",
    original_title: "Snow White and the Seven Dwarfs",
    is_adult: false,
    year: "1937",
    end_year: null,
    runtime: "83",
    genre: "Adventure, Animation, Family",
  },
  {
    tconst: "tt0032138",
    title_type: "movie",
    title: "The Wizard of Oz",
    original_title: "The Wizard of Oz",
    is_adult: false,
    year: "1939",
    end_year: null,
    runtime: "102",
    genre: "Adventure, Family, Fantasy",
  },
  {
    tconst: "tt0045152",
    title_type: "movie",
    title: "Singin' in the Rain",
    original_title: "Singin' in the Rain",
    is_adult: false,
    year: "1952",
    end_year: null,
    runtime: "103",
    genre: "Comedy, Musical, Romance",
  },
  {
    tconst: "tt0050083",
    title_type: "movie",
    title: "12 Angry Men",
    original_title: "12 Angry Men",
    is_adult: false,
    year: "1957",
    end_year: null,
    runtime: "96",
    genre: "Crime, Drama",
  },
  {
    tconst: "tt0068646",
    title_type: "movie",
    title: "The Godfather",
    original_title: "The Godfather",
    is_adult: false,
    year: "1972",
    end_year: null,
    runtime: "175",
    genre: "Crime, Drama",
  },
  {
    tconst: "tt0076759",
    title_type: "movie",
    title: "Star Wars",
    original_title: "Star Wars",
    is_adult: false,
    year: "1977",
    end_year: null,
    runtime: "121",
    genre: "Action, Adventure, Fantasy",
  },
  {
    tconst: "tt0080684",
    title_type: "movie",
    title: "Star Wars: Episode V - The Empire Strikes Back",
    original_title: "Star Wars: Episode V - The Empire Strikes Back",
    is_adult: false,
    year: "1980",
    end_year: null,
    runtime: "124",
    genre: "Action, Adventure, Fantasy",
  },
  {
    tconst: "tt0099685",
    title_type: "movie",
    title: "Goodfellas",
    original_title: "Goodfellas",
    is_adult: false,
    year: "1990",
    end_year: null,
    runtime: "146",
    genre: "Biography, Crime, Drama",
  },
  {
    tconst: "tt0108052",
    title_type: "movie",
    title: "Schindler's List",
    original_title: "Schindler's List",
    is_adult: false,
    year: "1993",
    end_year: null,
    runtime: "195",
    genre: "Biography, Drama, History",
  },
  {
    tconst: "tt0111161",
    title_type: "movie",
    title: "The Shawshank Redemption",
    original_title: "The Shawshank Redemption",
    is_adult: false,
    year: "1994",
    end_year: null,
    runtime: "142",
    genre: "Drama",
  },
  {
    tconst: "tt0120737",
    title_type: "movie",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    original_title: "The Lord of the Rings: The Fellowship of the Ring",
    is_adult: false,
    year: "2001",
    end_year: null,
    runtime: "178",
    genre: "Action, Adventure, Drama",
  },
  {
    tconst: "tt0133093",
    title_type: "movie",
    title: "The Matrix",
    original_title: "The Matrix",
    is_adult: false,
    year: "1999",
    end_year: null,
    runtime: "136",
    genre: "Action, Sci-Fi",
  },
  {
    tconst: "tt0167260",
    title_type: "movie",
    title: "The Lord of the Rings: The Return of the King",
    original_title: "The Lord of the Rings: The Return of the King",
    is_adult: false,
    year: "2003",
    end_year: null,
    runtime: "201",
    genre: "Action, Adventure, Drama",
  },
  {
    tconst: "tt0172495",
    title_type: "movie",
    title: "Gladiator",
    original_title: "Gladiator",
    is_adult: false,
    year: "2000",
    end_year: null,
    runtime: "155",
    genre: "Action, Adventure, Drama",
  },
  {
    tconst: "tt0245429",
    title_type: "movie",
    title: "Spirited Away",
    original_title: "Sen to Chihiro no kamikakushi",
    is_adult: false,
    year: "2001",
    end_year: null,
    runtime: "125",
    genre: "Animation, Adventure, Family",
  },
  {
    tconst: "tt00171612",
    title_type: "movie",
    title: "Moana",
    original_title: "Moana",
    is_adult: false,
    year: "1926",
    end_year: null,
    runtime: "85",
    genre: "Documentary",
  },
  {
    tconst: "2tt0029583",
    title_type: "movie",
    title: "Snow White and the Seven Dwarfs",
    original_title: "Snow White and the Seven Dwarfs",
    is_adult: false,
    year: "1937",
    end_year: null,
    runtime: "83",
    genre: "Adventure, Animation, Family",
  },
  {
    tconst: "tt0032138",
    title_type: "movie",
    title: "The Wizard of Oz",
    original_title: "The Wizard of Oz",
    is_adult: false,
    year: "1939",
    end_year: null,
    runtime: "102",
    genre: "Adventure, Family, Fantasy",
  },
  {
    tconst: "tt0045152",
    title_type: "movie",
    title: "Singin' in the Rain",
    original_title: "Singin' in the Rain",
    is_adult: false,
    year: "1952",
    end_year: null,
    runtime: "103",
    genre: "Comedy, Musical, Romance",
  },
  {
    tconst: "tt0050083",
    title_type: "movie",
    title: "12 Angry Men",
    original_title: "12 Angry Men",
    is_adult: false,
    year: "1957",
    end_year: null,
    runtime: "96",
    genre: "Crime, Drama",
  },
  {
    tconst: "tt0068646",
    title_type: "movie",
    title: "The Godfather",
    original_title: "The Godfather",
    is_adult: false,
    year: "1972",
    end_year: null,
    runtime: "175",
    genre: "Crime, Drama",
  },
  {
    tconst: "tt0076759",
    title_type: "movie",
    title: "Star Wars",
    original_title: "Star Wars",
    is_adult: false,
    year: "1977",
    end_year: null,
    runtime: "121",
    genre: "Action, Adventure, Fantasy",
  },
  {
    tconst: "tt0080684",
    title_type: "movie",
    title: "Star Wars: Episode V - The Empire Strikes Back",
    original_title: "Star Wars: Episode V - The Empire Strikes Back",
    is_adult: false,
    year: "1980",
    end_year: null,
    runtime: "124",
    genre: "Action, Adventure, Fantasy",
  },
  {
    tconst: "tt0099685",
    title_type: "movie",
    title: "Goodfellas",
    original_title: "Goodfellas",
    is_adult: false,
    year: "1990",
    end_year: null,
    runtime: "146",
    genre: "Biography, Crime, Drama",
  },
  {
    tconst: "tt0108052",
    title_type: "movie",
    title: "Schindler's List",
    original_title: "Schindler's List",
    is_adult: false,
    year: "1993",
    end_year: null,
    runtime: "195",
    genre: "Biography, Drama, History",
  },
  {
    tconst: "tt0111161",
    title_type: "movie",
    title: "The Shawshank Redemption",
    original_title: "The Shawshank Redemption",
    is_adult: false,
    year: "1994",
    end_year: null,
    runtime: "142",
    genre: "Drama",
  },
  {
    tconst: "tt0120737",
    title_type: "movie",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    original_title: "The Lord of the Rings: The Fellowship of the Ring",
    is_adult: false,
    year: "2001",
    end_year: null,
    runtime: "178",
    genre: "Action, Adventure, Drama",
  },
  {
    tconst: "tt0133093",
    title_type: "movie",
    title: "The Matrix",
    original_title: "The Matrix",
    is_adult: false,
    year: "1999",
    end_year: null,
    runtime: "136",
    genre: "Action, Sci-Fi",
  },
  {
    tconst: "tt0167260",
    title_type: "movie",
    title: "The Lord of the Rings: The Return of the King",
    original_title: "The Lord of the Rings: The Return of the King",
    is_adult: false,
    year: "2003",
    end_year: null,
    runtime: "201",
    genre: "Action, Adventure, Drama",
  },
  {
    tconst: "tt0172495",
    title_type: "movie",
    title: "Gladiator",
    original_title: "Gladiator",
    is_adult: false,
    year: "2000",
    end_year: null,
    runtime: "155",
    genre: "Action, Adventure, Drama",
  },
  {
    tconst: "tt0245429",
    title_type: "movie",
    title: "Spirited Away",
    original_title: "Sen to Chihiro no kamikakushi",
    is_adult: false,
    year: "2001",
    end_year: null,
    runtime: "125",
    genre: "Animation, Adventure, Family",
  },
];

export const MOCK_PRINCIPALS: ApiPrincipal[] = [
  {
    id: 1,
    category: "actor",
    job: null,
    characters: ["Moana"],
    tconst: "tt0017162",
    nconst: "nm0845808",
  },
  {
    id: 2,
    category: "actor",
    job: null,
    characters: ["Moana's Fiancé"],
    tconst: "tt0017162",
    nconst: "nm0264390",
  },
];

export const MOCK_NAMES: ApiName[] = [
  {
    nconst: "nm0000051",
    name: "James Mason",
    birth_year: "1909",
    death_year: "1984",
    primary_professions: "actor,producer,writer",
    known_for_titles: "tt0056193,tt0053125,tt0047522,tt0084855",
  },
  {
    nconst: "nm0000100",
    name: "Rowan Atkinson",
    birth_year: "1955",
    death_year: null,
    primary_professions: "actor,writer,producer",
    known_for_titles: "tt0274166,tt1634122,tt0110357,tt0118689",
  },
];
// Bonus
export const MOCK_TMDB_MOVIES = [
  {
    id: 1412113,
    title: "Squid Game: Making Season 2",
    overview:
      "From set designs to character arcs, get exclusive cast and director interviews on how Season 2 of the globally most-watched series was brought to life.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//jgrImRKhsRXaa6wlSsQPnFRUQbH.jpg",
    image: null,
    releaseData: "2025-01-02",
    rating: 8.51,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1214667,
    title: "Making Squid Game: The Challenge",
    overview:
      'Go behind the scenes and witness how the "Squid Game"-inspired reality show transformed from a scripted drama to a cutthroat, nail-biting competition.',
    backgroundImage:
      "https://image.tmdb.org/t/p/original//i9bhxhUBFZHorvK81GNKMJGj2Kt.jpg",
    image: "/78yTLvtsMntVN1cLfzBuZj870pe.jpg",
    releaseData: "2023-12-06",
    rating: 6.9,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1023915,
    title: "2073",
    overview:
      "Inspired by Chris Marker's iconic 1962 featurette La Jetée; the year is 2073—a not-so-distant dystopian future—and the setting is New San Francisco, the scorched-earth tech-dominant police state where democracy and personal freedom have been well and truly obliterated.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//721p2lNSGp2iSlUUukZwCzEKrnn.jpg",
    image: "/l67ir3kU53FYd6Vjwhqrkih1H1P.jpg",
    releaseData: "2024-12-27",
    rating: 7.011,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1422877,
    title: "Miss Italia Mustn't Die",
    overview: "",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//4uRVAQUgOOePIkEj7D0CPDVSQXr.jpg",
    image: "/1mOX8qO3QHNlhcEIoIwTvu1SHpD.jpg",
    releaseData: "2025-02-26",
    rating: 8,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 324558,
    title: "X-Rated: The Greatest Adult Movies of All Time",
    overview:
      "The evolution of adult cinema through the most influential films in history, a journey that begins in the 1970s and ends nowadays. An in-depth analysis of the success of the most prestigious erotic films, their impact on industry and society, and their influence on cinema and contemporary culture.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//3gw6ZMxVbfOQcQahGsmwdvFJPOa.jpg",
    image: "/1UgdqTHgwNivULiZvNcJ0Mj3skl.jpg",
    releaseData: "2015-02-06",
    rating: 6.4,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 899082,
    title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    overview:
      "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//g8dafKwLfaueQ5GK0qjKTkRCBAA.jpg",
    image: "/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
    releaseData: "2022-01-01",
    rating: 7.3,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 318256,
    title: "Hot Girls Wanted",
    overview:
      "A first-ever look at the realities of the professional “amateur” porn world and the steady stream of 18-to-19-year old girls entering into it.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//bV7eAcBrYb57PwjpQ2ODT6VyFPd.jpg",
    image: "/75ot83QOkc02vujyzmIbumQCU6Y.jpg",
    releaseData: "2015-01-24",
    rating: 6.1,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 773736,
    title: "TINA",
    overview:
      "Tina Turner overcame impossible odds to become one of the first female Black artists to reach a mainstream international audience. Her road to superstardom is an undeniable story of triumph over adversity. It’s the ultimate story of survival – and an inspirational story of our times.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//wuEiqcDu4Y0kQO6nXGVarKJGLtG.jpg",
    image: "/g2Fm6iZr2LNwy8Nz2tY8Wgdo4vp.jpg",
    releaseData: "2021-08-20",
    rating: 7.681,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1433947,
    title: "Who Is Luigi Mangione?",
    overview:
      "Writings and social media posts help to reveal the secret life and troubles of Luigi Mangione, the man accused of the brazen murder of United Healthcare CEO Brian Thompson and whom so many people are calling a hero.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//8HBfkTtnZS8gEK5jSgYZHBFyhlY.jpg",
    image: "/lfGZ8tjK4HVTRjmD5X9JIKDepGC.jpg",
    releaseData: "2025-02-17",
    rating: 6,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1262299,
    title: "El Apocalipsis de san Juan",
    overview:
      "Embark on an epic journey through time and faith with 'The Apocalypse of Saint John.' Join the Apostle John in a stunning visual narrative that unravels the visions of the End Times. Experience each vision like never before, with striking visual effects and epic scenes that immerse you in the apocalyptic narrative.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//8lreZPhAuNjGmqukZWzY9sORmyl.jpg",
    image: "/zzXU586n4uDBgMtVMPPQW7UJwu8.jpg",
    releaseData: "2024-10-07",
    rating: 10,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1426038,
    title: "Uncredited: The Story of Passinho",
    overview:
      "In this rousing documentary, a Brazilian street dancer training for a major contest dives deep into a culture that's given a voice to countless dancers.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//oXNil4Lv72bN00jSHE5ROkQt70M.jpg",
    image: "/wFpWFGjcUv1I8rnCyVgsozOzuEw.jpg",
    releaseData: "2025-02-20",
    rating: 6,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 426889,
    title: "Le Clitoris",
    overview:
      "Women are lucky, they get to have the only organ in the human body dedicated exclusively for pleasure: the clitoris! In this humorous and instructive animated documentary, find out its unrecognized anatomy and its unknown herstory.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//aLhtnH4pKHnD02ZfBGm2djwlNBH.jpg",
    image: "/p5i1yyQW6OpLfB59w7ZkX5lvBqD.jpg",
    releaseData: "2016-06-18",
    rating: 7.111,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 939099,
    title: "swingers ZwingerZ",
    overview: "",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//dzqvWTl5Y1B9P5nEivZPP8Y0WpU.jpg",
    image: "/lemo5hfG4w7Sm9mKjiIGmJ3hkYB.jpg",
    releaseData: "2022-03-20",
    rating: 4.5,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1022256,
    title: "Selena Gomez: My Mind & Me",
    overview:
      "After years in the limelight, Selena Gomez achieves unimaginable stardom. But just as she reaches a new peak, an unexpected turn pulls her into darkness. This uniquely raw and intimate documentary spans her six-year journey into a new light.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//u3MWQCdHyCK7IADtat4sVmBXd9U.jpg",
    image: "/usJxHVxT70lAA7AynnZlmPth7R3.jpg",
    releaseData: "2022-11-04",
    rating: 8.7,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 638039,
    title: "Penis Poetry",
    overview:
      "This is a poetic film about The Penis becoming a diary with a unique story to tell. Penis Poetry is made in collaboration with Andre Medeiros Martins who wrote on his lovers' penises his personal thoughts. Andre's words reflect how much our modern society glorifies the exhibition of The Penis, how much we worship it and how much social media and apps allowed us to share our most private parts with the world.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//2SQ167uvCEthEwV6bcIWscHHEf3.jpg",
    image: "/iIsVm0lQ7GzBPaLAQD3CjsF0iQe.jpg",
    releaseData: "2017-01-08",
    rating: 4.8,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1401905,
    title: "Don't Die: The Man Who Wants to Live Forever",
    overview:
      "In this documentary, wealthy entrepreneur Bryan Johnson puts his body and fortune on the line to defy aging and extend his life beyond all known limits.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//ey6HaUwo4CJoOYDlJ0M90ykJ0dt.jpg",
    image: "/2M0CF7UsbpQ45xGuVRhExAhUWBj.jpg",
    releaseData: "2025-01-01",
    rating: 6,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 438478,
    title: "Pornocracy: The New Sex Multinationals",
    overview:
      "Never before have we watched as much porn as today yet the traditional porn industry is dying. The arrival of web sites showing amateur clips has transformed the way porn is made and consumed. Behind this transformation lies one opaque multinational.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//2VFUh8spzyNbRNPyncIrFmSwBrd.jpg",
    image: "/kfa1KHSaewjv9sSrrHDdWNdroyv.jpg",
    releaseData: "2017-03-12",
    rating: 6.8,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1270880,
    title: "Katt Williams: Woke Foke",
    overview:
      "Comedian Katt Williams lets loose in real time as he hits the stage for Netflix's second livestreamed stand-up event.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//rGiiJARZf0SkyhIqf4j0mQQdycI.jpg",
    image: "/hjgAEcu8JEpeF7KEtmjTzPFD3uL.jpg",
    releaseData: "2024-05-04",
    rating: 5.5,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1246596,
    title: "The Walking Dead: The Return",
    overview:
      'Stars of "The Walking Dead," Andrew Lincoln and Danai Gurira, walk down memory lane and visit iconic locations where pivotal moments between their characters, Rick and Michonne, were filmed.',
    backgroundImage:
      "https://image.tmdb.org/t/p/original//kBmwtsPTG0P79oyoTBhaKfCxvSl.jpg",
    image: "/3clopfmZ8x6s1reWC6fxgXkysZz.jpg",
    releaseData: "2024-02-15",
    rating: 7.356,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1041513,
    title: "Encanto at the Hollywood Bowl",
    overview:
      'Step into Casa Madrigal for a special concert spectacular as the original voice cast of Disney Animation\'s Oscar®-winning "Encanto," Stephanie Beatriz, Adassa, Carolina Gaitán, Jessica Darrow, Diane Guerrero, Mauro Castillo, Angie Cepeda and Olga Merediz, along with special guests including Colombian superstar Carlos Vives, reunites for "Encanto at the Hollywood Bowl." This unprecedented concert experience gives you a front-row seat to the musical extravaganza celebrating the global phenomenon.',
    backgroundImage:
      "https://image.tmdb.org/t/p/original//tU3mnpFLOAp2Ia6vHvGIw8ewJQb.jpg",
    image: "/sa3Ku5yNVjp8NloWxJoI9dQjvOi.jpg",
    releaseData: "2022-12-27",
    rating: 7,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1412113,
    title: "Squid Game: Making Season 2",
    overview:
      "From set designs to character arcs, get exclusive cast and director interviews on how Season 2 of the globally most-watched series was brought to life.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//jgrImRKhsRXaa6wlSsQPnFRUQbH.jpg",
    image: null,
    releaseData: "2025-01-02",
    rating: 8.51,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1214667,
    title: "Making Squid Game: The Challenge",
    overview:
      'Go behind the scenes and witness how the "Squid Game"-inspired reality show transformed from a scripted drama to a cutthroat, nail-biting competition.',
    backgroundImage:
      "https://image.tmdb.org/t/p/original//i9bhxhUBFZHorvK81GNKMJGj2Kt.jpg",
    image: "/78yTLvtsMntVN1cLfzBuZj870pe.jpg",
    releaseData: "2023-12-06",
    rating: 6.9,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1023915,
    title: "2073",
    overview:
      "Inspired by Chris Marker's iconic 1962 featurette La Jetée; the year is 2073—a not-so-distant dystopian future—and the setting is New San Francisco, the scorched-earth tech-dominant police state where democracy and personal freedom have been well and truly obliterated.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//721p2lNSGp2iSlUUukZwCzEKrnn.jpg",
    image: "/l67ir3kU53FYd6Vjwhqrkih1H1P.jpg",
    releaseData: "2024-12-27",
    rating: 7.011,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1422877,
    title: "Miss Italia Mustn't Die",
    overview: "",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//4uRVAQUgOOePIkEj7D0CPDVSQXr.jpg",
    image: "/1mOX8qO3QHNlhcEIoIwTvu1SHpD.jpg",
    releaseData: "2025-02-26",
    rating: 8,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 324558,
    title: "X-Rated: The Greatest Adult Movies of All Time",
    overview:
      "The evolution of adult cinema through the most influential films in history, a journey that begins in the 1970s and ends nowadays. An in-depth analysis of the success of the most prestigious erotic films, their impact on industry and society, and their influence on cinema and contemporary culture.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//3gw6ZMxVbfOQcQahGsmwdvFJPOa.jpg",
    image: "/1UgdqTHgwNivULiZvNcJ0Mj3skl.jpg",
    releaseData: "2015-02-06",
    rating: 6.4,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 899082,
    title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    overview:
      "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//g8dafKwLfaueQ5GK0qjKTkRCBAA.jpg",
    image: "/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
    releaseData: "2022-01-01",
    rating: 7.3,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 318256,
    title: "Hot Girls Wanted",
    overview:
      "A first-ever look at the realities of the professional “amateur” porn world and the steady stream of 18-to-19-year old girls entering into it.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//bV7eAcBrYb57PwjpQ2ODT6VyFPd.jpg",
    image: "/75ot83QOkc02vujyzmIbumQCU6Y.jpg",
    releaseData: "2015-01-24",
    rating: 6.1,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 773736,
    title: "TINA",
    overview:
      "Tina Turner overcame impossible odds to become one of the first female Black artists to reach a mainstream international audience. Her road to superstardom is an undeniable story of triumph over adversity. It’s the ultimate story of survival – and an inspirational story of our times.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//wuEiqcDu4Y0kQO6nXGVarKJGLtG.jpg",
    image: "/g2Fm6iZr2LNwy8Nz2tY8Wgdo4vp.jpg",
    releaseData: "2021-08-20",
    rating: 7.681,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1433947,
    title: "Who Is Luigi Mangione?",
    overview:
      "Writings and social media posts help to reveal the secret life and troubles of Luigi Mangione, the man accused of the brazen murder of United Healthcare CEO Brian Thompson and whom so many people are calling a hero.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//8HBfkTtnZS8gEK5jSgYZHBFyhlY.jpg",
    image: "/lfGZ8tjK4HVTRjmD5X9JIKDepGC.jpg",
    releaseData: "2025-02-17",
    rating: 6,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1262299,
    title: "El Apocalipsis de san Juan",
    overview:
      "Embark on an epic journey through time and faith with 'The Apocalypse of Saint John.' Join the Apostle John in a stunning visual narrative that unravels the visions of the End Times. Experience each vision like never before, with striking visual effects and epic scenes that immerse you in the apocalyptic narrative.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//8lreZPhAuNjGmqukZWzY9sORmyl.jpg",
    image: "/zzXU586n4uDBgMtVMPPQW7UJwu8.jpg",
    releaseData: "2024-10-07",
    rating: 10,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1426038,
    title: "Uncredited: The Story of Passinho",
    overview:
      "In this rousing documentary, a Brazilian street dancer training for a major contest dives deep into a culture that's given a voice to countless dancers.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//oXNil4Lv72bN00jSHE5ROkQt70M.jpg",
    image: "/wFpWFGjcUv1I8rnCyVgsozOzuEw.jpg",
    releaseData: "2025-02-20",
    rating: 6,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 426889,
    title: "Le Clitoris",
    overview:
      "Women are lucky, they get to have the only organ in the human body dedicated exclusively for pleasure: the clitoris! In this humorous and instructive animated documentary, find out its unrecognized anatomy and its unknown herstory.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//aLhtnH4pKHnD02ZfBGm2djwlNBH.jpg",
    image: "/p5i1yyQW6OpLfB59w7ZkX5lvBqD.jpg",
    releaseData: "2016-06-18",
    rating: 7.111,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 939099,
    title: "swingers ZwingerZ",
    overview: "",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//dzqvWTl5Y1B9P5nEivZPP8Y0WpU.jpg",
    image: "/lemo5hfG4w7Sm9mKjiIGmJ3hkYB.jpg",
    releaseData: "2022-03-20",
    rating: 4.5,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1022256,
    title: "Selena Gomez: My Mind & Me",
    overview:
      "After years in the limelight, Selena Gomez achieves unimaginable stardom. But just as she reaches a new peak, an unexpected turn pulls her into darkness. This uniquely raw and intimate documentary spans her six-year journey into a new light.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//u3MWQCdHyCK7IADtat4sVmBXd9U.jpg",
    image: "/usJxHVxT70lAA7AynnZlmPth7R3.jpg",
    releaseData: "2022-11-04",
    rating: 8.7,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 638039,
    title: "Penis Poetry",
    overview:
      "This is a poetic film about The Penis becoming a diary with a unique story to tell. Penis Poetry is made in collaboration with Andre Medeiros Martins who wrote on his lovers' penises his personal thoughts. Andre's words reflect how much our modern society glorifies the exhibition of The Penis, how much we worship it and how much social media and apps allowed us to share our most private parts with the world.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//2SQ167uvCEthEwV6bcIWscHHEf3.jpg",
    image: "/iIsVm0lQ7GzBPaLAQD3CjsF0iQe.jpg",
    releaseData: "2017-01-08",
    rating: 4.8,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1401905,
    title: "Don't Die: The Man Who Wants to Live Forever",
    overview:
      "In this documentary, wealthy entrepreneur Bryan Johnson puts his body and fortune on the line to defy aging and extend his life beyond all known limits.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//ey6HaUwo4CJoOYDlJ0M90ykJ0dt.jpg",
    image: "/2M0CF7UsbpQ45xGuVRhExAhUWBj.jpg",
    releaseData: "2025-01-01",
    rating: 6,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 438478,
    title: "Pornocracy: The New Sex Multinationals",
    overview:
      "Never before have we watched as much porn as today yet the traditional porn industry is dying. The arrival of web sites showing amateur clips has transformed the way porn is made and consumed. Behind this transformation lies one opaque multinational.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//2VFUh8spzyNbRNPyncIrFmSwBrd.jpg",
    image: "/kfa1KHSaewjv9sSrrHDdWNdroyv.jpg",
    releaseData: "2017-03-12",
    rating: 6.8,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1270880,
    title: "Katt Williams: Woke Foke",
    overview:
      "Comedian Katt Williams lets loose in real time as he hits the stage for Netflix's second livestreamed stand-up event.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//rGiiJARZf0SkyhIqf4j0mQQdycI.jpg",
    image: "/hjgAEcu8JEpeF7KEtmjTzPFD3uL.jpg",
    releaseData: "2024-05-04",
    rating: 5.5,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1246596,
    title: "The Walking Dead: The Return",
    overview:
      'Stars of "The Walking Dead," Andrew Lincoln and Danai Gurira, walk down memory lane and visit iconic locations where pivotal moments between their characters, Rick and Michonne, were filmed.',
    backgroundImage:
      "https://image.tmdb.org/t/p/original//kBmwtsPTG0P79oyoTBhaKfCxvSl.jpg",
    image: "/3clopfmZ8x6s1reWC6fxgXkysZz.jpg",
    releaseData: "2024-02-15",
    rating: 7.356,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1041513,
    title: "Encanto at the Hollywood Bowl",
    overview:
      'Step into Casa Madrigal for a special concert spectacular as the original voice cast of Disney Animation\'s Oscar®-winning "Encanto," Stephanie Beatriz, Adassa, Carolina Gaitán, Jessica Darrow, Diane Guerrero, Mauro Castillo, Angie Cepeda and Olga Merediz, along with special guests including Colombian superstar Carlos Vives, reunites for "Encanto at the Hollywood Bowl." This unprecedented concert experience gives you a front-row seat to the musical extravaganza celebrating the global phenomenon.',
    backgroundImage:
      "https://image.tmdb.org/t/p/original//tU3mnpFLOAp2Ia6vHvGIw8ewJQb.jpg",
    image: "/sa3Ku5yNVjp8NloWxJoI9dQjvOi.jpg",
    releaseData: "2022-12-27",
    rating: 7,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1412113,
    title: "Squid Game: Making Season 2",
    overview:
      "From set designs to character arcs, get exclusive cast and director interviews on how Season 2 of the globally most-watched series was brought to life.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//jgrImRKhsRXaa6wlSsQPnFRUQbH.jpg",
    image: null,
    releaseData: "2025-01-02",
    rating: 8.51,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1214667,
    title: "Making Squid Game: The Challenge",
    overview:
      'Go behind the scenes and witness how the "Squid Game"-inspired reality show transformed from a scripted drama to a cutthroat, nail-biting competition.',
    backgroundImage:
      "https://image.tmdb.org/t/p/original//i9bhxhUBFZHorvK81GNKMJGj2Kt.jpg",
    image: "/78yTLvtsMntVN1cLfzBuZj870pe.jpg",
    releaseData: "2023-12-06",
    rating: 6.9,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1023915,
    title: "2073",
    overview:
      "Inspired by Chris Marker's iconic 1962 featurette La Jetée; the year is 2073—a not-so-distant dystopian future—and the setting is New San Francisco, the scorched-earth tech-dominant police state where democracy and personal freedom have been well and truly obliterated.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//721p2lNSGp2iSlUUukZwCzEKrnn.jpg",
    image: "/l67ir3kU53FYd6Vjwhqrkih1H1P.jpg",
    releaseData: "2024-12-27",
    rating: 7.011,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1422877,
    title: "Miss Italia Mustn't Die",
    overview: "",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//4uRVAQUgOOePIkEj7D0CPDVSQXr.jpg",
    image: "/1mOX8qO3QHNlhcEIoIwTvu1SHpD.jpg",
    releaseData: "2025-02-26",
    rating: 8,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 324558,
    title: "X-Rated: The Greatest Adult Movies of All Time",
    overview:
      "The evolution of adult cinema through the most influential films in history, a journey that begins in the 1970s and ends nowadays. An in-depth analysis of the success of the most prestigious erotic films, their impact on industry and society, and their influence on cinema and contemporary culture.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//3gw6ZMxVbfOQcQahGsmwdvFJPOa.jpg",
    image: "/1UgdqTHgwNivULiZvNcJ0Mj3skl.jpg",
    releaseData: "2015-02-06",
    rating: 6.4,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 899082,
    title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    overview:
      "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//g8dafKwLfaueQ5GK0qjKTkRCBAA.jpg",
    image: "/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
    releaseData: "2022-01-01",
    rating: 7.3,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 318256,
    title: "Hot Girls Wanted",
    overview:
      "A first-ever look at the realities of the professional “amateur” porn world and the steady stream of 18-to-19-year old girls entering into it.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//bV7eAcBrYb57PwjpQ2ODT6VyFPd.jpg",
    image: "/75ot83QOkc02vujyzmIbumQCU6Y.jpg",
    releaseData: "2015-01-24",
    rating: 6.1,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 773736,
    title: "TINA",
    overview:
      "Tina Turner overcame impossible odds to become one of the first female Black artists to reach a mainstream international audience. Her road to superstardom is an undeniable story of triumph over adversity. It’s the ultimate story of survival – and an inspirational story of our times.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//wuEiqcDu4Y0kQO6nXGVarKJGLtG.jpg",
    image: "/g2Fm6iZr2LNwy8Nz2tY8Wgdo4vp.jpg",
    releaseData: "2021-08-20",
    rating: 7.681,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1433947,
    title: "Who Is Luigi Mangione?",
    overview:
      "Writings and social media posts help to reveal the secret life and troubles of Luigi Mangione, the man accused of the brazen murder of United Healthcare CEO Brian Thompson and whom so many people are calling a hero.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//8HBfkTtnZS8gEK5jSgYZHBFyhlY.jpg",
    image: "/lfGZ8tjK4HVTRjmD5X9JIKDepGC.jpg",
    releaseData: "2025-02-17",
    rating: 6,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1262299,
    title: "El Apocalipsis de san Juan",
    overview:
      "Embark on an epic journey through time and faith with 'The Apocalypse of Saint John.' Join the Apostle John in a stunning visual narrative that unravels the visions of the End Times. Experience each vision like never before, with striking visual effects and epic scenes that immerse you in the apocalyptic narrative.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//8lreZPhAuNjGmqukZWzY9sORmyl.jpg",
    image: "/zzXU586n4uDBgMtVMPPQW7UJwu8.jpg",
    releaseData: "2024-10-07",
    rating: 10,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1426038,
    title: "Uncredited: The Story of Passinho",
    overview:
      "In this rousing documentary, a Brazilian street dancer training for a major contest dives deep into a culture that's given a voice to countless dancers.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//oXNil4Lv72bN00jSHE5ROkQt70M.jpg",
    image: "/wFpWFGjcUv1I8rnCyVgsozOzuEw.jpg",
    releaseData: "2025-02-20",
    rating: 6,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 426889,
    title: "Le Clitoris",
    overview:
      "Women are lucky, they get to have the only organ in the human body dedicated exclusively for pleasure: the clitoris! In this humorous and instructive animated documentary, find out its unrecognized anatomy and its unknown herstory.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//aLhtnH4pKHnD02ZfBGm2djwlNBH.jpg",
    image: "/p5i1yyQW6OpLfB59w7ZkX5lvBqD.jpg",
    releaseData: "2016-06-18",
    rating: 7.111,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 939099,
    title: "swingers ZwingerZ",
    overview: "",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//dzqvWTl5Y1B9P5nEivZPP8Y0WpU.jpg",
    image: "/lemo5hfG4w7Sm9mKjiIGmJ3hkYB.jpg",
    releaseData: "2022-03-20",
    rating: 4.5,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1022256,
    title: "Selena Gomez: My Mind & Me",
    overview:
      "After years in the limelight, Selena Gomez achieves unimaginable stardom. But just as she reaches a new peak, an unexpected turn pulls her into darkness. This uniquely raw and intimate documentary spans her six-year journey into a new light.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//u3MWQCdHyCK7IADtat4sVmBXd9U.jpg",
    image: "/usJxHVxT70lAA7AynnZlmPth7R3.jpg",
    releaseData: "2022-11-04",
    rating: 8.7,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 638039,
    title: "Penis Poetry",
    overview:
      "This is a poetic film about The Penis becoming a diary with a unique story to tell. Penis Poetry is made in collaboration with Andre Medeiros Martins who wrote on his lovers' penises his personal thoughts. Andre's words reflect how much our modern society glorifies the exhibition of The Penis, how much we worship it and how much social media and apps allowed us to share our most private parts with the world.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//2SQ167uvCEthEwV6bcIWscHHEf3.jpg",
    image: "/iIsVm0lQ7GzBPaLAQD3CjsF0iQe.jpg",
    releaseData: "2017-01-08",
    rating: 4.8,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1401905,
    title: "Don't Die: The Man Who Wants to Live Forever",
    overview:
      "In this documentary, wealthy entrepreneur Bryan Johnson puts his body and fortune on the line to defy aging and extend his life beyond all known limits.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//ey6HaUwo4CJoOYDlJ0M90ykJ0dt.jpg",
    image: "/2M0CF7UsbpQ45xGuVRhExAhUWBj.jpg",
    releaseData: "2025-01-01",
    rating: 6,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 438478,
    title: "Pornocracy: The New Sex Multinationals",
    overview:
      "Never before have we watched as much porn as today yet the traditional porn industry is dying. The arrival of web sites showing amateur clips has transformed the way porn is made and consumed. Behind this transformation lies one opaque multinational.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//2VFUh8spzyNbRNPyncIrFmSwBrd.jpg",
    image: "/kfa1KHSaewjv9sSrrHDdWNdroyv.jpg",
    releaseData: "2017-03-12",
    rating: 6.8,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1270880,
    title: "Katt Williams: Woke Foke",
    overview:
      "Comedian Katt Williams lets loose in real time as he hits the stage for Netflix's second livestreamed stand-up event.",
    backgroundImage:
      "https://image.tmdb.org/t/p/original//rGiiJARZf0SkyhIqf4j0mQQdycI.jpg",
    image: "/hjgAEcu8JEpeF7KEtmjTzPFD3uL.jpg",
    releaseData: "2024-05-04",
    rating: 5.5,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1246596,
    title: "The Walking Dead: The Return",
    overview:
      'Stars of "The Walking Dead," Andrew Lincoln and Danai Gurira, walk down memory lane and visit iconic locations where pivotal moments between their characters, Rick and Michonne, were filmed.',
    backgroundImage:
      "https://image.tmdb.org/t/p/original//kBmwtsPTG0P79oyoTBhaKfCxvSl.jpg",
    image: "/3clopfmZ8x6s1reWC6fxgXkysZz.jpg",
    releaseData: "2024-02-15",
    rating: 7.356,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 1041513,
    title: "Encanto at the Hollywood Bowl",
    overview:
      'Step into Casa Madrigal for a special concert spectacular as the original voice cast of Disney Animation\'s Oscar®-winning "Encanto," Stephanie Beatriz, Adassa, Carolina Gaitán, Jessica Darrow, Diane Guerrero, Mauro Castillo, Angie Cepeda and Olga Merediz, along with special guests including Colombian superstar Carlos Vives, reunites for "Encanto at the Hollywood Bowl." This unprecedented concert experience gives you a front-row seat to the musical extravaganza celebrating the global phenomenon.',
    backgroundImage:
      "https://image.tmdb.org/t/p/original//tU3mnpFLOAp2Ia6vHvGIw8ewJQb.jpg",
    image: "/sa3Ku5yNVjp8NloWxJoI9dQjvOi.jpg",
    releaseData: "2022-12-27",
    rating: 7,
    duration: "1h 49m",
    genres: ["Action", "Adventure", "Comedy"],
  },
];
